### ISSUE TITLE
Enable plotting to POC2 by default

### ISSUE THREAD

**Issue by damccull** [JohnnyFFM/XPlotterGui#3]
From what I gather in the code, this GUI kicks of a POC1 plot by default, and when done plotting it can convert to POC2 as it copies to the new location. This is inefficient, of course, and your modded version of Xplotter already supports direct to POC2. My suggestion is to add a checkbox that enables plotting direct to POC2 through the GUI so we can take advantage of the SSD cache and other neat features too.

**Comment by JohnnyFFM** [comment]
agreed! will be in next release!

**Comment by JohnnyFFM** [comment]
[XPlotter_GUI_robocopy.zip](https://github.com/JohnnyFFM/XPlotterGui/files/2134157/XPlotter_GUI_robocopy.zip)
PreRelease attached, completely removed PoC1 support.
